// <auto-generated />
using System;
using System.Collections.Generic;
using ImageGen.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ImageGen.Data.Migrations
{
    [DbContext(typeof(ImageGenDbContext))]
    [Migration("20260425223642_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ImageGen.Models.ImageGenerationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<int>("Size")
                        .HasColumnType("integer")
                        .HasColumnName("size");

                    b.Property<int>("Style")
                        .HasColumnType("integer")
                        .HasColumnName("style");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Cost", "ImageGen.Models.ImageGenerationResult.Cost#CostEstimate", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric")
                                .HasColumnName("Cost");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TokenUsed", "ImageGen.Models.ImageGenerationResult.TokenUsed#TokenCount", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<long>("Value")
                                .HasColumnType("bigint")
                                .HasColumnName("TokenUsed");
                        });

                    b.HasKey("Id")
                        .HasName("pk_image_gen_results");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_image_gen_results_session_id");

                    b.ToTable("image_gen_results", (string)null);
                });

            modelBuilder.Entity("ImageGen.Models.ImageGenerationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AiModelId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ai_model_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastGeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_generated_at");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Configuration", "ImageGen.Models.ImageGenerationSession.Configuration#ImageGenerationConfiguration", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Language")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Language");

                            b1.Property<int>("Quality")
                                .HasColumnType("integer")
                                .HasColumnName("Quality");

                            b1.Property<int>("Size")
                                .HasColumnType("integer")
                                .HasColumnName("Size");

                            b1.Property<int>("Style")
                                .HasColumnType("integer")
                                .HasColumnName("Style");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TotalCost", "ImageGen.Models.ImageGenerationSession.TotalCost#CostEstimate", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric")
                                .HasColumnName("TotalCost");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TotalTokens", "ImageGen.Models.ImageGenerationSession.TotalTokens#TokenCount", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<long>("Value")
                                .HasColumnType("bigint")
                                .HasColumnName("TotalTokens");
                        });

                    b.HasKey("Id")
                        .HasName("pk_image_gen_sessions");

                    b.ToTable("image_gen_sessions", (string)null);
                });

            modelBuilder.Entity("ImageGen.Models.ImageGenerationResult", b =>
                {
                    b.HasOne("ImageGen.Models.ImageGenerationSession", null)
                        .WithMany("Results")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_image_gen_results_image_gen_sessions_session_id");
                });

            modelBuilder.Entity("ImageGen.Models.ImageGenerationSession", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
