// <auto-generated />
using System;
using System.Collections.Generic;
using CodeGen.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CodeGen.Data.Migrations
{
    [DbContext(typeof(CodeGenDbContext))]
    [Migration("20260424062906_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CodeGen.Models.CodeGenerationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt");

                    b.Property<int>("QualityLevel")
                        .HasColumnType("integer")
                        .HasColumnName("quality_level");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Cost", "CodeGen.Models.CodeGenerationResult.Cost#CostEstimate", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric")
                                .HasColumnName("Cost");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TokenUsed", "CodeGen.Models.CodeGenerationResult.TokenUsed#TokenCount", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<long>("Value")
                                .HasColumnType("bigint")
                                .HasColumnName("TokenUsed");
                        });

                    b.HasKey("Id")
                        .HasName("pk_codegen_results");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_codegen_results_session_id");

                    b.ToTable("codegen_results", (string)null);
                });

            modelBuilder.Entity("CodeGen.Models.CodeGenerationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AiModelId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ai_model_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastGeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_generated_at");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Configuration", "CodeGen.Models.CodeGenerationSession.Configuration#CodeGenerationConfiguration", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<bool>("IncludeComments")
                                .HasColumnType("boolean")
                                .HasColumnName("IncludeComments");

                            b1.Property<long>("MaxTokens")
                                .HasColumnType("bigint")
                                .HasColumnName("MaxTokens");

                            b1.Property<int>("Style")
                                .HasColumnType("integer")
                                .HasColumnName("Style");

                            b1.Property<float>("Temperature")
                                .HasColumnType("real")
                                .HasColumnName("Temperature");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TotalCost", "CodeGen.Models.CodeGenerationSession.TotalCost#CostEstimate", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric")
                                .HasColumnName("TotalCost");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TotalTokens", "CodeGen.Models.CodeGenerationSession.TotalTokens#TokenCount", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<long>("Value")
                                .HasColumnType("bigint")
                                .HasColumnName("TotalTokens");
                        });

                    b.HasKey("Id")
                        .HasName("pk_codegen_sessions");

                    b.ToTable("codegen_sessions", (string)null);
                });

            modelBuilder.Entity("CodeGen.Models.CodeGenerationResult", b =>
                {
                    b.HasOne("CodeGen.Models.CodeGenerationSession", null)
                        .WithMany("Results")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_codegen_results_codegen_sessions_session_id");
                });

            modelBuilder.Entity("CodeGen.Models.CodeGenerationSession", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
