// <auto-generated />
using System;
using System.Collections.Generic;
using ChatBot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChatBot.Data.Migrations
{
    [DbContext(typeof(ChatDbContext))]
    [Migration("20260424062601_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChatBot.Models.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<int>("Sender")
                        .HasColumnType("integer")
                        .HasColumnName("sender");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Cost", "ChatBot.Models.ChatMessage.Cost#CostEstimate", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric")
                                .HasColumnName("Cost");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TokenUsed", "ChatBot.Models.ChatMessage.TokenUsed#TokenCount", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<long>("Value")
                                .HasColumnType("bigint")
                                .HasColumnName("TokenUsed");
                        });

                    b.HasKey("Id")
                        .HasName("pk_chat_messages");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_chat_messages_session_id");

                    b.ToTable("chat_messages", (string)null);
                });

            modelBuilder.Entity("ChatBot.Models.ChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AiModelId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ai_model_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTime>("LastSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sent_at");

                    b.Property<int>("SessionStatus")
                        .HasColumnType("integer")
                        .HasColumnName("session_status");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Configuration", "ChatBot.Models.ChatSession.Configuration#ChatConfiguration", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<long>("MaxTokens")
                                .HasColumnType("bigint")
                                .HasColumnName("MaxTokens");

                            b1.Property<string>("SystemPrompt")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("SystemPrompt");

                            b1.Property<float>("Temperature")
                                .HasColumnType("real")
                                .HasColumnName("Temperature");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TotalCost", "ChatBot.Models.ChatSession.TotalCost#CostEstimate", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric")
                                .HasColumnName("TotalCost");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TotalTokens", "ChatBot.Models.ChatSession.TotalTokens#TokenCount", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<long>("Value")
                                .HasColumnType("bigint")
                                .HasColumnName("TotalTokens");
                        });

                    b.HasKey("Id")
                        .HasName("pk_chats");

                    b.ToTable("chats", (string)null);
                });

            modelBuilder.Entity("ChatBot.Models.ChatMessage", b =>
                {
                    b.HasOne("ChatBot.Models.ChatSession", null)
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_chat_messages_chats_session_id");
                });

            modelBuilder.Entity("ChatBot.Models.ChatSession", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
