// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Translate.Data;

#nullable disable

namespace Translate.Data.Migrations
{
    [DbContext(typeof(TranslateDbContext))]
    [Migration("20260424063109_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Translate.Models.TranslationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("OriginalText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_text");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTime>("TranslatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("translated_at");

                    b.Property<string>("TranslatedText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("translated_text");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Cost", "Translate.Models.TranslationResult.Cost#CostEstimate", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric")
                                .HasColumnName("Cost");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TokenUsed", "Translate.Models.TranslationResult.TokenUsed#TokenCount", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<long>("Value")
                                .HasColumnType("bigint")
                                .HasColumnName("TokenUsed");
                        });

                    b.HasKey("Id")
                        .HasName("pk_translation_results");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_translation_results_session_id");

                    b.ToTable("translation_results", (string)null);
                });

            modelBuilder.Entity("Translate.Models.TranslationSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AiModelId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ai_model_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTime>("LastTranslatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_translated_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Configuration", "Translate.Models.TranslationSession.Configuration#TranslationConfiguration", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("DetailLevel")
                                .HasColumnType("integer")
                                .HasColumnName("DetailLevel");

                            b1.Property<string>("SourceLanguage")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("SourceLanguage");

                            b1.Property<string>("TargetLanguage")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("TargetLanguage");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TotalCost", "Translate.Models.TranslationSession.TotalCost#CostEstimate", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric")
                                .HasColumnName("TotalCost");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TotalTokens", "Translate.Models.TranslationSession.TotalTokens#TokenCount", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<long>("Value")
                                .HasColumnType("bigint")
                                .HasColumnName("TotalTokens");
                        });

                    b.HasKey("Id")
                        .HasName("pk_translation_sessions");

                    b.ToTable("translation_sessions", (string)null);
                });

            modelBuilder.Entity("Translate.Models.TranslationResult", b =>
                {
                    b.HasOne("Translate.Models.TranslationSession", null)
                        .WithMany("Results")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_translation_results_translation_sessions_session_id");
                });

            modelBuilder.Entity("Translate.Models.TranslationSession", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
