// <auto-generated />
using System;
using System.Collections.Generic;
using CodeDebug.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CodeDebug.Data.Migrations
{
    [DbContext(typeof(CodeDebugDbContext))]
    [Migration("20260425222412_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CodeDebug.Models.CodeDebugReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("analyzed_at");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("Language")
                        .HasColumnType("integer")
                        .HasColumnName("language");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Cost", "CodeDebug.Models.CodeDebugReport.Cost#CostEstimate", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric")
                                .HasColumnName("Cost");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "IssueCount", "CodeDebug.Models.CodeDebugReport.IssueCount#IssueCount", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("IssueCount");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TokenUsed", "CodeDebug.Models.CodeDebugReport.TokenUsed#TokenCount", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<long>("Value")
                                .HasColumnType("bigint")
                                .HasColumnName("TokenUsed");
                        });

                    b.HasKey("Id")
                        .HasName("pk_code_debug_reports");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_code_debug_reports_session_id");

                    b.ToTable("code_debug_reports", (string)null);
                });

            modelBuilder.Entity("CodeDebug.Models.CodeDebugSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AiModelId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ai_model_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("LastAnalyzedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_analyzed_at");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Configuration", "CodeDebug.Models.CodeDebugSession.Configuration#CodeDebugConfiguration", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Depth")
                                .HasColumnType("integer")
                                .HasColumnName("Depth");

                            b1.Property<bool>("IncludeSuggestions")
                                .HasColumnType("boolean")
                                .HasColumnName("IncludeSuggestions");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TotalCost", "CodeDebug.Models.CodeDebugSession.TotalCost#CostEstimate", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric")
                                .HasColumnName("TotalCost");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "TotalTokens", "CodeDebug.Models.CodeDebugSession.TotalTokens#TokenCount", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<long>("Value")
                                .HasColumnType("bigint")
                                .HasColumnName("TotalTokens");
                        });

                    b.HasKey("Id")
                        .HasName("pk_code_debug_sessions");

                    b.ToTable("code_debug_sessions", (string)null);
                });

            modelBuilder.Entity("CodeDebug.Models.CodeDebugReport", b =>
                {
                    b.HasOne("CodeDebug.Models.CodeDebugSession", null)
                        .WithMany("Reports")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_code_debug_reports_code_debug_sessions_session_id");
                });

            modelBuilder.Entity("CodeDebug.Models.CodeDebugSession", b =>
                {
                    b.Navigation("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
